--CREATE DATABASE EroiVSMostri
--USE EroiVSMostri
--GO

--inserisco il flag della vittoria e il tempo
CREATE TABLE Eroe(
ID INT NOT NULL PRIMARY KEY IDENTITY,
Nome VARCHAR(255) UNIQUE,
GiocatoreID INT NOT NULL FOREIGN KEY REFERENCES Giocatore(ID),
ClasseID INT NOT NULL FOREIGN KEY REFERENCES Classe(ID),
LivelloID INT NOT NULL FOREIGN KEY REFERENCES Livello(ID),
ArmaID INT NOT NULL FOREIGN KEY REFERENCES Arma(ID),
PuntiAccumulati INT,
Vittoria BIT,
TempoDiGioco TIME
)

CREATE TABLE Giocatore(
ID INT NOT NULL PRIMARY KEY IDENTITY,
Nome VARCHAR(255),
Ruolo VARCHAR(255),
)

CREATE TABLE Mostro(
ID INT NOT NULL PRIMARY KEY IDENTITY,
Nome VARCHAR(255) UNIQUE,
ClasseID INT NOT NULL FOREIGN KEY REFERENCES Classe(ID),
LivelloID INT NOT NULL FOREIGN KEY REFERENCES Livello(ID),
ArmaID INT NOT NULL FOREIGN KEY REFERENCES Arma(ID),
)

CREATE TABLE Arma(
ID INT NOT NULL PRIMARY KEY IDENTITY,
Nome VARCHAR(255) UNIQUE,
ClasseID INT NOT NULL FOREIGN KEY REFERENCES Classe(ID),
Danni INT,
)

CREATE TABLE Livello(
ID INT NOT NULL PRIMARY KEY IDENTITY,
Num INT NOT NULL,
PuntiVita INT,
)

INSERT INTO Livello
VALUES (1,20),(2,40),(3,60),(4,80),(5,100)

SELECT * FROM Livello

CREATE TABLE Classe(
ID INT NOT NULL PRIMARY KEY IDENTITY,
Valore BIT,
Nome VARCHAR(30),
)

INSERT INTO Classe 
VALUES (1,'Mago'),(1,'Guerriero'),(0,'Orco'),(0,'SignoreDelMale'),(0,'Cultista')

SELECT * FROM Classe

INSERT INTO Arma
VALUES ('Spada',2,10),('Pistola',2,15),('Bastone',3,8),('Lancia',5,10),('Fuoco',4,20),('Bacchetta',1,20),('Pietra',3,5),('MagiaNera',4,25),('MagiaBianca',1,20)

DELETE FROM Arma 

INSERT INTO Giocatore 
VALUES ('Aldo', 'Utente'),('Max','Admin')

INSERT INTO Eroe
VALUES('Ercole',1,2,1,1,0,0,'00:00:00')

SELECT * FROM Arma
SELECT * FROM Livello
SELECT * FROM Classe
SELECT * FROM Mostro 
SELECT * FROM Eroe
SELECT * FROM Giocatore 

INSERT INTO Mostro
VALUES('Troll',3,2,4),('Voldemort', 4,1,5),('Tor',3,1,4),('Eran',5,1,3)

UPDATE Eroe SET PuntiAccumulati = 10,LivelloID = 2 WHERE ID = 14